// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using sinup.ServiceLayer.Data;

#nullable disable

namespace ProjectTWO.Migrations
{
    [DbContext(typeof(ProjectDB))]
    [Migration("20230803125436_project1")]
    partial class project1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjectTWO.ServiceLayer.Model.Categoryes", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "Dairy products",
                            Name = "Sut"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "Non mahsulotlari",
                            Name = "Non"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "Ichimliklar turli hil",
                            Name = "Ichimliklar"
                        });
                });

            modelBuilder.Entity("ProjectTWO.ServiceLayer.Model.Product", b =>
                {
                    b.Property<int>("ProdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProdId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<string>("ProdCat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("ProdId");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            ProdId = 1,
                            Name = "Non",
                            Price = 20,
                            ProdCat = "Non",
                            Quantity = 3500
                        },
                        new
                        {
                            ProdId = 2,
                            Name = "Bolichka",
                            Price = 20,
                            ProdCat = "Non",
                            Quantity = 8000
                        },
                        new
                        {
                            ProdId = 3,
                            Name = "Pitsa",
                            Price = 3,
                            ProdCat = "Non",
                            Quantity = 30000
                        },
                        new
                        {
                            ProdId = 4,
                            Name = "Coca-cola",
                            Price = 10,
                            ProdCat = "Ichimliklar",
                            Quantity = 11900
                        },
                        new
                        {
                            ProdId = 5,
                            Name = "Pepsi",
                            Price = 10,
                            ProdCat = "Ichimliklar",
                            Quantity = 11900
                        },
                        new
                        {
                            ProdId = 6,
                            Name = "Fanta",
                            Price = 10,
                            ProdCat = "Ichimliklar",
                            Quantity = 11900
                        },
                        new
                        {
                            ProdId = 7,
                            Name = "Sgushenka",
                            Price = 10,
                            ProdCat = "Sut",
                            Quantity = 28990
                        },
                        new
                        {
                            ProdId = 8,
                            Name = "Qaymoq",
                            Price = 10,
                            ProdCat = "Sut",
                            Quantity = 13900
                        },
                        new
                        {
                            ProdId = 9,
                            Name = "Sut",
                            Price = 10,
                            ProdCat = "Sut",
                            Quantity = 10990
                        });
                });

            modelBuilder.Entity("ProjectTWO.ServiceLayer.Model.Sellers", b =>
                {
                    b.Property<int>("SellerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SellerId"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SellerId");

                    b.ToTable("sellers");

                    b.HasData(
                        new
                        {
                            SellerId = 1,
                            Age = 21,
                            Name = "Sarvar",
                            Password = "sarvar0303",
                            Phone = "+998 950940303"
                        });
                });

            modelBuilder.Entity("ProjectTWO.ServiceLayer.Model.Sellings_product", b =>
                {
                    b.Property<int>("prodID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("prodID"));

                    b.Property<string>("ProdName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProdPrice")
                        .HasColumnType("integer");

                    b.Property<int>("ProdQty")
                        .HasColumnType("integer");

                    b.Property<int>("Total")
                        .HasColumnType("integer");

                    b.HasKey("prodID");

                    b.ToTable("selings_products");
                });

            modelBuilder.Entity("sinup.ServiceLayer.User.ServiceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("serviceModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "G'ulomjonov",
                            LastName = "Sarvar",
                            Password = "sarvar0303",
                            Phone = "+998 950940303",
                            UserName = "murodovich"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
